/**
 * Hill Rider — procedural terrain module.
 *
 * `heightAt(x)` is a pure function of world-x (no seed, no precomputed
 * arrays, no chunk bookkeeping): a small handful of sine layers at
 * incommensurate wavelengths ("rolling hills") plus a smoothed 1-D value
 * noise layer (a hashed lattice, cosine-interpolated between integer
 * points) for irregularity, plus occasional localized raised-cosine bumps
 * ("jump" features) layered on top. Because it's a pure function, the strip
 * is trivially "endless" — querying further out just evaluates the same
 * formula at a bigger x, there is nothing to generate-ahead-of-time or run
 * out of. The first ~500 units are eased flat for a fair, safe spawn.
 *
 * `slopeAt(x, half)` sits on top of `heightAt` using the exact same
 * front/rear sampling shape vehicle.js's stepVehicle uses for its own
 * ground-contact angle (front = heightAt(x+half), rear = heightAt(x-half),
 * angle = atan2(front-rear, 2*half)) — so a test harness can independently
 * recompute "what the slope actually is at this x" and compare it directly
 * against the live vehicle's chassis angle, instead of eyeballing it.
 *
 * Coin/fuel placement is slot-indexed (coinAtSlot/fuelAtSlot), not
 * range-scanned: each integer slot index maps to at most one item via a
 * hash roll, so a caller advancing an integer slot cursor forward as the
 * camera progresses can never regenerate or skip a slot regardless of
 * exactly where a frame's lookahead boundary lands.
 */

// ---------------------------------------------------------------------------
// Deterministic hashes (GLSL-style sine-hash) — no seed: "procedurally
// generated" here means generated by the formula, not re-rollable per run.
// Two independently-tuned magic-constant families so the coin grid, fuel
// grid and terrain noise don't visibly correlate with each other.
// ---------------------------------------------------------------------------
function hash1(i) {
  const s = Math.sin(i * 127.1 + 43.11) * 43758.5453123;
  return s - Math.floor(s); // [0,1)
}
function hash2(i) {
  const s = Math.sin(i * 311.7 + 71.13) * 24634.6345;
  return s - Math.floor(s); // [0,1)
}

function smoothstep01(t) {
  const c = Math.max(0, Math.min(1, t));
  return c * c * (3 - 2 * c);
}

/** Smooth 1-D value noise in roughly [-1, 1]: hashed lattice at integer
 * multiples of `scale`, cosine/smoothstep-interpolated between them. */
function valueNoise(x, scale) {
  const p = x / scale;
  const i0 = Math.floor(p);
  const f = p - i0;
  const v0 = hash1(i0) * 2 - 1;
  const v1 = hash1(i0 + 1) * 2 - 1;
  return v0 + (v1 - v0) * smoothstep01(f);
}

// ---------------------------------------------------------------------------
// Terrain shape tuning
// ---------------------------------------------------------------------------
// The vehicle's full-throttle equilibrium climb angle (see vehicle.js:
// SLOPE_GRAVITY vs THROTTLE_ACCEL) is a hard physical limit on how steep a
// SUSTAINED slope can be before the vehicle simply cannot power through it
// from a standing start — only a run-up (built on an earlier downhill) can
// clear anything steeper. That's authentic genre tension, but only once the
// player has had room to learn the controls and build speed; a steep,
// sustained slope landing at/near the spawn point (discovered directly: an
// early tuning had a ~55deg sustained climb around x=450-540, well inside
// the old 500-unit ease-in, that trapped a constant-full-throttle vehicle
// rocking in place for minutes) is just unfair. EASE_IN_DISTANCE keeps the
// immediate spawn flat; SOFT_ZONE_END extends a gentler (not zero) amplitude
// well past that so there's real room to build speed before full difficulty
// terrain can appear.
const EASE_IN_DISTANCE = 1400;
const SOFT_ZONE_END = 4200;
const SOFT_ZONE_FLOOR = 0.55;
const GROWTH_DISTANCE = 26000; // terrain gets gradually bumpier out to here
const GROWTH_CAP = 1.15;

// Amplitudes are tuned so the vehicle's full-throttle equilibrium climb
// angle (~44deg, see vehicle.js) keeps comfortable headroom over ordinary
// terrain's typical/worst-realistic slope, verified empirically with a
// constant-full-throttle bot driven for tens of thousands of units (see
// scratchpad physics tests): each sine layer's own max slope is bounded by
// construction (amp/wavelength), so combined worst-case is a simple sum.
const SINE_LAYERS = [
  { amp: 90, wavelength: 900, phase: 0.7 }, // broad rolling hills, ~5.7deg max
  { amp: 28, wavelength: 340, phase: 2.1 }, // medium bumps, ~4.7deg max
  { amp: 10, wavelength: 120, phase: 4.4 }, // small texture, ~4.8deg max
];
// Tamed from an earlier, much bumpier value: the value-noise layer's
// worst-case local slope contribution scales with NOISE_AMP/NOISE_SCALE, and
// at the original amplitude it was comfortably the single biggest
// contributor to the sustained-45deg+ stretches that produced the spawn-trap
// above (see terrain_test notes) -- the sine layers alone are well-behaved.
const NOISE_AMP = 14;
const NOISE_SCALE = 220;

const FEATURE_SPACING = 820; // "jump" ramp feature slot width
const FEATURE_CHANCE = 0.45;

function featureAt(slotIndex) {
  if (hash1(slotIndex * 3.317 + 91.7) >= FEATURE_CHANCE) return null;
  const centerJitter = (hash1(slotIndex * 7.11 + 3.2) - 0.5) * FEATURE_SPACING * 0.5;
  const center = slotIndex * FEATURE_SPACING + FEATURE_SPACING * 0.5 + centerJitter;
  // height/width is deliberately kept modest (max ratio ~0.54) so a ramp's
  // steepest point stays a launchable "hit it with speed" incline rather
  // than an unclimbable wall -- a raised-cosine bump's own max slope is
  // 0.5*height*pi/width regardless of position, so an early tuning with
  // height up to 160 over width down to 130 (ratio 1.23) produced ~110deg
  // peaks, comfortably steeper than vertical-derivative territory and a
  // guaranteed dead end wherever one landed. Caught directly by the same
  // full-throttle-bot sweep that found the sine/noise spawn-trap above.
  const height = 30 + hash2(slotIndex * 5.53 + 8.9) * 40; // 30-70
  const width = 130 + hash1(slotIndex * 9.77 + 2.1) * 110; // 130-240
  return { center, height, width };
}

/** Positive-only raised-cosine bumps (ramps only ever add height, giving a
 * smooth launch-hill shape, never a lowered dip). */
function rampContribution(x) {
  const slot = Math.floor(x / FEATURE_SPACING);
  let total = 0;
  for (let s = slot - 1; s <= slot + 1; s++) {
    const f = featureAt(s);
    if (!f) continue;
    const d = x - f.center;
    if (Math.abs(d) < f.width) {
      total += f.height * 0.5 * (1 + Math.cos((Math.PI * d) / f.width));
    }
  }
  return total;
}

/** Elevation above baseline (positive = higher up). */
function elevation(x) {
  let e = 0;
  for (const l of SINE_LAYERS) e += l.amp * Math.sin(x / l.wavelength + l.phase);
  e += NOISE_AMP * valueNoise(x, NOISE_SCALE);
  e += rampContribution(x);

  const ease = smoothstep01(x / EASE_IN_DISTANCE);
  e *= ease;

  // Gentler-than-full amplitude for a stretch beyond the flat spawn (a
  // "tutorial zone" with real but forgiving hills), ramping up to full
  // difficulty by SOFT_ZONE_END.
  const softFrac = SOFT_ZONE_FLOOR + (1 - SOFT_ZONE_FLOOR) * smoothstep01((x - EASE_IN_DISTANCE) / (SOFT_ZONE_END - EASE_IN_DISTANCE));
  e *= Math.min(1, Math.max(SOFT_ZONE_FLOOR, softFrac));

  const growth = Math.min(1 + Math.max(0, x) / GROWTH_DISTANCE, GROWTH_CAP);
  e *= growth;

  return e;
}

/** World Y (canvas convention: bigger Y = lower/down) of the ground at x. */
export function heightAt(x) {
  return -elevation(x);
}

/** Ground-tangent angle at x, sampled the same way the vehicle samples its
 * own front/rear wheel contact (see vehicle.js stepVehicle). */
export function slopeAt(x, half = 26) {
  const front = heightAt(x + half);
  const rear = heightAt(x - half);
  return Math.atan2(front - rear, 2 * half);
}

// ---------------------------------------------------------------------------
// Collectibles — slot-indexed, deterministic, at most one item per slot.
// ---------------------------------------------------------------------------
export const COIN_SLOT = 110;
// A full tank at sustained full throttle covers roughly 14000 units (~67s;
// verified empirically in the scratchpad physics tests). FUEL_SLOT/
// FUEL_CHANCE is tuned so a canister appears roughly every ~2000 units on
// average (FUEL_SLOT/FUEL_CHANCE) -- about 7 opportunities across a full
// tank's worth of distance, each restoring 45%. Collecting most of them
// keeps the tank comfortable; missing several in a row (e.g. chasing coins
// instead) creates genuine risk of running dry. An earlier tuning (260/0.65,
// a canister roughly every ~400 units) made fuel management trivial --
// canisters would show up every 1-2 seconds of driving, never a real
// resource decision.
export const FUEL_SLOT = 1000;

const COIN_CHANCE = 0.55;
const FUEL_CHANCE = 0.5;
const COIN_FLOAT_MIN = 40;
const COIN_FLOAT_MAX = 95;
const FUEL_FLOAT = 40;
const COIN_MIN_X = 500; // keep the eased-flat spawn strip clear of clutter
const FUEL_MIN_X = 700;

/** Coin at integer slot `s`, or null if that slot rolled empty. */
export function coinAtSlot(s) {
  const slotX = s * COIN_SLOT;
  if (slotX < COIN_MIN_X) return null;
  if (hash1(s * 4.213 + 17.7) >= COIN_CHANCE) return null;
  const jitter = (hash1(s * 9.31 + 2.2) - 0.5) * COIN_SLOT * 0.6;
  const x = slotX + COIN_SLOT * 0.5 + jitter;
  const floatH = COIN_FLOAT_MIN + hash2(s * 1.7 + 5.5) * (COIN_FLOAT_MAX - COIN_FLOAT_MIN);
  return { id: `c${s}`, kind: 'coin', x, y: heightAt(x) - floatH };
}

/** Fuel canister at integer slot `s`, or null if that slot rolled empty.
 * Sits low (near ground) so it's reliably grabbable by normal driving,
 * never gated behind a risky jump the way a coin sometimes is. */
export function fuelAtSlot(s) {
  const slotX = s * FUEL_SLOT;
  if (slotX < FUEL_MIN_X) return null;
  if (hash2(s * 6.7 + 31.1) >= FUEL_CHANCE) return null;
  const jitter = (hash1(s * 3.3 + 9.9) - 0.5) * FUEL_SLOT * 0.5;
  const x = slotX + FUEL_SLOT * 0.5 + jitter;
  return { id: `f${s}`, kind: 'fuel', x, y: heightAt(x) - FUEL_FLOAT };
}

// ---------------------------------------------------------------------------
// Rendering — neon-vector: solid dark fill down to below-frame, glowing
// stroke along the top edge. A cheap 2-layer far silhouette (drawn first,
// caller applies its own parallax translate) gives depth without needing
// any bitmap asset.
// ---------------------------------------------------------------------------
const SAMPLE_STEP = 14;

export function drawTerrain(ctx, xMin, xMax, bottomY, colors) {
  const pts = [];
  for (let x = Math.floor(xMin / SAMPLE_STEP) * SAMPLE_STEP; x <= xMax + SAMPLE_STEP; x += SAMPLE_STEP) {
    pts.push({ x, y: heightAt(x) });
  }
  if (pts.length < 2) return;

  ctx.beginPath();
  ctx.moveTo(pts[0].x, bottomY);
  for (const p of pts) ctx.lineTo(p.x, p.y);
  ctx.lineTo(pts[pts.length - 1].x, bottomY);
  ctx.closePath();
  ctx.fillStyle = colors.fill;
  ctx.fill();

  ctx.beginPath();
  ctx.moveTo(pts[0].x, pts[0].y);
  for (const p of pts) ctx.lineTo(p.x, p.y);
  ctx.strokeStyle = colors.edge;
  ctx.lineWidth = 3;
  ctx.shadowColor = colors.edge;
  ctx.shadowBlur = 14;
  ctx.stroke();
  ctx.shadowBlur = 0;
}

function farRidgeAt(x) {
  return -(60 * Math.sin(x / 1400 + 1.1) + 26 * Math.sin(x / 540 + 3.0));
}

export function drawFarRidge(ctx, xMin, xMax, bottomY, color) {
  const step = 40;
  const pts = [];
  for (let x = Math.floor(xMin / step) * step; x <= xMax + step; x += step) {
    pts.push({ x, y: farRidgeAt(x) });
  }
  if (pts.length < 2) return;
  ctx.beginPath();
  ctx.moveTo(pts[0].x, bottomY);
  for (const p of pts) ctx.lineTo(p.x, p.y);
  ctx.lineTo(pts[pts.length - 1].x, bottomY);
  ctx.closePath();
  ctx.fillStyle = color;
  ctx.fill();
}
